spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/spring-bucks?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: @P1ssword