management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql
    url: jdbc:h2:mem:spring-bucks
    username: sa
    password: sa
  h2:
    console:
      enabled: true